### ISSUE TITLE
Bug: Admin panel actions do not work in Safari and Epiphany

### ISSUE THREAD

**Issue by berezovskyi** [ArchiveBox/ArchiveBox#658]
#### Describe the bug

"No action selected." error is returned from the admin pages when trying to run actions like Archive via Safari.

#### Steps to reproduce

1. Open http://%HOST%/admin/core/snapshot/?p=1 page
2. Select a few entries by ticking the checkboxes.
3. Click the Archive button.

#### Screenshots or log output

Before:

![image](https://user-images.githubusercontent.com/64734/109391876-9bcd5300-7919-11eb-8071-f3423fb6b2cb.jpeg)

After:

![image](https://user-images.githubusercontent.com/64734/109391883-a556bb00-7919-11eb-9a7b-e893febcc43e.jpeg)

- Safari 14.0.3 on latest Catalina update.
- Content blockers disabled.
- Cross-site tracking prevention disabled.
- Extensions enabled are Instapaper and Bitwarden but should not affect this.

Console does not show any errors except the favicon 404s. This exact sequence of steps works perfectly well in FF, Chrome, Brave on macOS. DOES NOT work on GNOME Web (aka Epiphany) on Linux. I tried to searching for Django Admin problems with actions in Webkit but maybe I was not making specific enough queries to pinpoint this.

#### ArchiveBox version

```logs
replace this line with the *full*, unshortened output of running `archivebox version`
```

```
ArchiveBox v0.5.6
Cpython Linux Linux-5.8.0-43-generic-x86_64-with-glibc2.28 x86_64 (in Docker)

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.5.6          valid     /usr/local/bin/archivebox
 √  PYTHON_BINARY         v3.9.1          valid     /usr/local/bin/python3.9
 √  DJANGO_BINARY         v3.1.3          valid     /usr/local/lib/python3.9/site-packages/django/bin/django-admin.py
 √  CURL_BINARY           v7.64.0         valid     /usr/bin/curl
 √  WGET_BINARY           v1.20.1         valid     /usr/bin/wget
 √  NODE_BINARY           v15.8.0         valid     /usr/bin/node
 √  SINGLEFILE_BINARY     v0.1.14         valid     /node/node_modules/single-file/cli/single-file
 √  READABILITY_BINARY    v0.1.0          valid     /node/node_modules/readability-extractor/readability-extractor
 √  MERCURY_BINARY        v1.0.0          valid     /node/node_modules/@postlight/mercury-parser/cli.js
 √  GIT_BINARY            v2.20.1         valid     /usr/bin/git
 √  YOUTUBEDL_BINARY      v2021.02.04.1   valid     /usr/local/bin/youtube-dl
 √  CHROME_BINARY         v88.0.4324.146  valid     /usr/bin/chromium
 √  RIPGREP_BINARY        v0.10.0         valid     /usr/bin/rg

[i] Source-code locations:
 √  PACKAGE_DIR           22 files        valid     /app/archivebox
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled
 -  COOKIES_FILE          -               disabled

[i] Data locations:
 √  OUTPUT_DIR            13 files        valid     /data
 √  SOURCES_DIR           202 files       valid     ./sources
 √  LOGS_DIR              0 files         valid     ./logs
 √  ARCHIVE_DIR           4381 files      valid     ./archive
 √  CONFIG_FILE           1.1 KB          valid     ./ArchiveBox.conf
 √  SQL_INDEX             35.1 MB         valid     ./index.sqlite3
```

**Comment by pirate** [comment]
Interesting, I had not run into this myself in Safari on macOS Catalina in the past, but I'll investigate again now that I'm on Big Sur.

**Comment by pirate** [comment]
Fixed in 68a506e. Will be out with the v0.6 release. Comment back if you still have any trouble after that release is out and I'll reopen the issue.

**Comment by mdbraber** [comment]
Seems that this bug is back? Experiencing the same issue with the `dev` branch (and 0.6.2) on Safari 14.1 on Big Sur (11.3.1)

**Comment by rcarmo** [comment]
I can confirm this is still an issue with both desktop and mobile Safari, which makes it hard/impossible to use on an iPad.

**Comment by aidenmitchell** [comment]
Still an issue as of v0.6.2 on iPadOS 15.2db2

**Comment by pirate** [comment]
It's fixed in v0.6.3 @aidenmitchell , you can run the pre-release version safely by following these instructions: https://github.com/ArchiveBox/ArchiveBox#install-and-run-a-specific-github-branch

**Comment by aidenmitchell** [comment]
@pirate Just updated to dev branch, still not working unfortunately.

**Comment by pirate** [comment]
Sorry can you re-pull and try again now, I just merged another PR that helps fix it https://github.com/ArchiveBox/ArchiveBox/pull/885

**Comment by aidenmitchell** [comment]
Works now, thank you!

**Comment by pirate** [comment]
Great, thanks for helping test. I'm going to close this for now as fixed, anyone arriving here can do the same step to run the pre-release version early, or wait for the v0.6.3 release to land.
